# Generated by Django 3.2.8 on 2021-10-10 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=15)),
                ('isbn_num', models.CharField(max_length=15, verbose_name='book num')),
                ('genre', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('library_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('BT', 'BookTaken'), ('BR', 'BookReturned')], default='BT', max_length=2)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBooks',
            fields=[
                ('library_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetapp.book')),
                ('last_library_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleetapp.libraryactivity')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetapp.library')),
            ],
        ),
        migrations.AddField(
            model_name='libraryactivity',
            name='library_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetapp.librarybooks'),
        ),
        migrations.AddField(
            model_name='libraryactivity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
