# Generated by Django 3.2.8 on 2021-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryactivity',
            name='checked_in_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
